name: Deploy pygoat
on:
  push:
    branches: [ master ]
jobs:
  conviso_production:
    runs-on:
      - convisoappsec
    container:
      image: convisoappsec/flowcli
      env:
        FLOW_API_KEY: ${{ secrets.FLOW_API_KEY }}
        FLOW_PROJECT_CODE: WDmhjRB_qGoJvG1y
    steps:
      - uses: actions/checkout@v2

      - name: Run Flow SAST
        run: flow sast run

      - name: Run Flow SCA
        run: flow sca run -v INFO

  conviso_k8s_staging:
    runs-on:
      - convisoappsec
    container:
      image: convisoappsec/flowcli
      env:
        FLOW_API_URL: https://flow-saas.staging.convisoappsec.com
        FLOW_API_KEY: ${{ secrets.FLOW_API_KEY_K8S_STAGING }}
        FLOW_PROJECT_CODE: 4z7QeQ11XGcxLNIS
    steps:
      - uses: actions/checkout@v2

      - name: Run Flow Deploy to send src to codereview
        run: flow deploy create -f env_vars with values

      - name: Run Flow SAST
        run: flow sast run
        env:
          FLOW_SASTBOX_TAG: 1.7.6-rc.0

      - name: Run Flow SCA
        run: flow sca run -v INFO
