name: Deploy pygoat
on:
  push:
    branches: [ master ]
jobs:
 conviso:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       FLOW_API_KEY:  ${{secrets.FLOW_API_KEY}}
   steps:
   - uses: actions/checkout@v2
   - name: Run Flow SAST
     run: flow sast run --project-code "WDmhjRB_qGoJvG1y"
   - name: Run Flow SCA
     run: flow sca run --project-code "WDmhjRB_qGoJvG1y" -v INFO
