name: Deploy pygoat
on:
  push:
    branches: [ master ]
jobs:
  conviso:
    runs-on:
      - convisoappsec
    container:
      image: convisoappsec/flowcli
      env:
        FLOW_API_KEY:  ${{ secrets.FLOW_API_KEY }}
        FLOW_PROJECT_CODE: WDmhjRB_qGoJvG1y
    steps:
      - uses: actions/checkout@v2
      - name: Run Flow SAST
        run: flow sast run
      - name: Run Flow SCA
        run: flow sca run -v INFO

