name: Deploy pygoat
on:
  push:
    branches: [ master ]
jobs:
  conviso_production:
    runs-on:
      - convisoappsec
    container:
      image: convisoappsec/convisocli:1.10.2-rc.1
      env:
        FLOW_API_KEY: ${{ secrets.FLOW_API_KEY }}
        FLOW_PROJECT_CODE: U1FszD2IYCWPLnp2
    steps:
      - uses: actions/checkout@v2

      - name: Run Flow Deploy to send src to codereview
        run: conviso deploy create -f env_vars with values
      
      - name: Run Flow SAST
        run: conviso sast run

      - name: Run Flow SCA
        run: conviso sca run

#  conviso_k8s_staging:
#    runs-on:
#      - convisoappsec
#    container:
#      image: convisoappsec/flowcli
#      env:
#        FLOW_API_URL: https://staging.convisoappsec.com
#        FLOW_API_KEY: ${{ secrets.FLOW_API_KEY_K8S_STAGING }}
#        FLOW_PROJECT_CODE: P3AKhlJ_ZepYnZB6
#    steps:
#      - uses: actions/checkout@v2

#      - name: Run Flow Deploy to send src to codereview
#        run: flow deploy create -f env_vars with values

#      - name: Run Flow SAST
#        run: flow sast run

#      - name: Run Flow SCA
#        run: flow sca run -v INFO

#  conviso_ec2_staging_01:
#    runs-on:
#      - convisoappsec
#    container:
#      image: convisoappsec/flowcli:1.10.1-rc.7
#      env:
#        FLOW_API_URL: https://homologa.conviso.com.br
#        FLOW_API_KEY: ${{ secrets.FLOW_API_KEY_EC2_STAGING }}
#        #FLOW_PROJECT_CODE: P3AKhlJ_ZepYnZB6
#        FLOW_PROJECT_CODE: meleca
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Run Flow Deploy to send src to codereview
#        run: flow deploy create -f env_vars with values
#
#      - name: Run Flow SAST
#        run: flow sast run
#
#      - name: Run Flow SCA
#        run: flow sca run -v INFO

#  conviso_ec2_staging_02:
#    runs-on:
#      - convisoappsec
#    container:
#      image: convisoappsec/flowcli
#      env:
#        FLOW_API_URL: https://homologa.convisoappsec.com
#        FLOW_API_KEY: ${{ secrets.FLOW_API_KEY_EC2_STAGING }}
#        FLOW_PROJECT_CODE: P3AKhlJ_ZepYnZB6
#    steps:
#      - uses: actions/checkout@v2

#      - name: Run Flow Deploy to send src to codereview
#        run: flow deploy create -f env_vars with values

#      - name: Run Flow SAST
#        run: flow sast run

#      - name: Run Flow SCA
#        run: flow sca run -v INFO
